[package]
name = "s-lang"
version = "0.1.0"
authors = ["sanket1729 <sanket1729@gmail.com>"]
edition = "2021"
rust-version = "1.61.0"

[lib]
name = "s_lang"
path = "src/lib.rs"

[[bin]]
name = "simpc"
path = "src/main.rs"

[dependencies]
base64 = "0.21.2"
hex-conservative = "0.1.1"
pest = "2.1.3"
pest_derive = "2.7.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
simplicity-lang = "0.2.0"
miniscript = "11.0.0"
